---
title: xuyangchen的博客
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: ''
keyword: ''
url: ''
baseurl: ''
nav:
  home: "/"
  tags: "/tags.html"
footer:
  since: 2017
author: xuyangchen
nickname: x-y-c
bio: ''
avatar: "/assets/img/profile.jpg"
search: true
nightMode: true
comments:
  disqus: false
  disqus_url: https://liaokeyu.disqus.com/embed.js
mathjax: true
social-share: true
social-share-items:
- wechat
- weibo
- douban
- twitter
theme-color: default
postPatterns: circuitBoard
sns:
  github: "//github.com/x-y-c"
recommend-tags: true
recommend-condition-size: 12
paginate: 6
paginate_path: page:num
exclude:
- node_modules
- dev
- package.json
- gulpfile.js
- ".gitignore"
- README.md
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
RSS: false
permalink: "/:year/:month/:day/:title.html"
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-admin